{
	"id": "oval:com.redhat.cve:def:201912781",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "Incorrect HTTP detection with reverse-proxy connecting via HTTPS (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2019-12781",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-12781",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: An HTTP detection flaw was discovered in Django.  If deployed behind a reverse-proxy connecting to Django via HTTPS,  django.http.HttpRequest.scheme() incorrectly detected client requests made using HTTP as using HTTPS.  This resulted in incorrect results for is_secure() and build_absolute_uri(), and HTTP requests were not correctly redirected to HTTPS in accordance with SECURE_SSL_REDIRECT. \n            STATEMENT: This issue does not affect any versions of python-django as shipped with Red Hat Update Infrastructure for Cloud Providers as the load balancer should not be configured to forward HTTP requests.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2023-09-07"
			},
			"cve": [
				{
					"text": "CVE-2019-12781",
					"cvss3": "4.8/CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
					"cwe": "(CWE-358|CWE-444)",
					"href": "https://access.redhat.com/security/cve/CVE-2019-12781",
					"impact": "moderate",
					"public": "20190701"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Will not fix",
						"component": [
							"python-django",
							"python-django-bash-completion",
							"python-django-doc"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openstack-optools:10",
					"cpe:/a:redhat:openstack-optools:10::el7",
					"cpe:/a:redhat:openstack:10",
					"cpe:/a:redhat:openstack:10::el7"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014003",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014004",
										"comment": "python-django is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014001",
										"comment": "python-django-bash-completion is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014002",
										"comment": "python-django-bash-completion is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014005",
										"comment": "python-django-doc is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:20169014006",
										"comment": "python-django-doc is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20115034003",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20115034004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
