{
	"id": "oval:com.redhat.unaffected:def:202024583",
	"version": "631",
	"class": "vulnerability",
	"metadata": {
		"title": "Unaffected components for: CVE-2020-24583 django: incorrect permissions on intermediate-level directories on Python 3.7+ (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2020-24583",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2020-24583",
				"source": "CVE"
			}
		],
		"description": "Red Hat's versions of the associated software have been determined to NOT be affected by CVE-2020-24583.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {},
			"affected": {},
			"affected_cpe_list": {},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201912781003",
										"comment": "python2-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.unaffected:tst:201712794002",
										"comment": "python2-django is not installed"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:201912781001",
										"comment": "python-django is installed"
									},
									{
										"test_ref": "oval:com.redhat.unaffected:tst:201712794004",
										"comment": "python-django is not installed"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20134120011",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20134120012",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
