{
	"id": "oval:com.redhat.rhsa:def:20203185",
	"version": "635",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2020:3185: python-pillow security update (Important)",
		"reference": [
			{
				"ref_id": "RHSA-2020:3185",
				"ref_url": "https://access.redhat.com/errata/RHSA-2020:3185",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2020-11538",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2020-11538",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2020-5313",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2020-5313",
				"source": "CVE"
			}
		],
		"description": "The python-pillow packages contain a Python image processing library that provides extensive file format support, an efficient internal representation, and powerful image-processing capabilities.\n\nSecurity Fix(es):\n\n* python-pillow: out-of-bounds reads/writes in the parsing of SGI image files in expandrow/expandrow2 (CVE-2020-11538)\n\n* python-pillow: out-of-bounds read in ImagingFliDecode when loading FLI images (CVE-2020-5313)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Important",
			"updated": {
				"date": "2020-07-28"
			},
			"cve": [
				{
					"text": "CVE-2020-11538",
					"cvss3": "8.1/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"cwe": "CWE-122",
					"href": "https://access.redhat.com/security/cve/CVE-2020-11538",
					"impact": "important",
					"public": "20200701"
				},
				{
					"text": "CVE-2020-5313",
					"cvss3": "8.2/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
					"cwe": "CWE-125",
					"href": "https://access.redhat.com/security/cve/CVE-2020-5313",
					"impact": "moderate",
					"public": "20200103"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_eus:8.8",
					"cpe:/a:redhat:rhel_eus:8.8::appstream",
					"cpe:/a:redhat:rhel_eus:8.8::crb",
					"cpe:/a:redhat:rhel_eus:8.8::highavailability",
					"cpe:/a:redhat:rhel_eus:8.8::resilientstorage",
					"cpe:/a:redhat:rhel_eus:8.8::sap",
					"cpe:/a:redhat:rhel_eus:8.8::sap_hana",
					"cpe:/a:redhat:rhel_eus:8.8::supplementary",
					"cpe:/o:redhat:rhel_eus:8.8",
					"cpe:/o:redhat:rhel_eus:8.8::baseos"
				]
			},
			"rights": "Copyright 2020 Red Hat, Inc.",
			"issued": {
				"date": "2020-07-28"
			},
			"bugzilla": [
				{
					"text": "CVE-2020-5313 python-pillow: out-of-bounds read in ImagingFliDecode when loading FLI images",
					"href": "https://bugzilla.redhat.com/1789532",
					"id": "1789532"
				},
				{
					"text": "CVE-2020-11538 python-pillow: out-of-bounds reads/writes in the parsing of SGI image files in expandrow/expandrow2",
					"href": "https://bugzilla.redhat.com/1852814",
					"id": "1852814"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20203185001",
						"comment": "python3-pillow is earlier than 0:5.1.1-12.el8_2"
					},
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20200580002",
						"comment": "python3-pillow is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20191992005",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
