{
	"id": "oval:com.redhat.rhsa:def:20244260",
	"version": "636",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2024:4260: python-idna security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2024:4260",
				"ref_url": "https://access.redhat.com/errata/RHSA-2024:4260",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2024-3651",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-3651",
				"source": "CVE"
			}
		],
		"description": "The hsakmt packages include a thunk library for AMD's Heterogeneous System Architecture (HSA) Linux kernel driver (amdkfd).\n\nSecurity Fix(es):\n\n* python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode() (CVE-2024-3651)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-07-02"
			},
			"cve": [
				{
					"text": "CVE-2024-3651",
					"cvss3": "6.5/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2024-3651",
					"impact": "moderate",
					"public": "20240412"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:8",
					"cpe:/a:redhat:enterprise_linux:8::appstream",
					"cpe:/a:redhat:enterprise_linux:8::crb",
					"cpe:/a:redhat:enterprise_linux:8::highavailability",
					"cpe:/a:redhat:enterprise_linux:8::nfv",
					"cpe:/a:redhat:enterprise_linux:8::realtime",
					"cpe:/a:redhat:enterprise_linux:8::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:8::sap",
					"cpe:/a:redhat:enterprise_linux:8::sap_hana",
					"cpe:/a:redhat:enterprise_linux:8::supplementary",
					"cpe:/o:redhat:enterprise_linux:8",
					"cpe:/o:redhat:enterprise_linux:8::baseos"
				]
			},
			"rights": "Copyright 2024 Red Hat, Inc.",
			"issued": {
				"date": "2024-07-02"
			},
			"bugzilla": [
				{
					"text": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()",
					"href": "https://bugzilla.redhat.com/2274779",
					"id": "2274779"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.cve:tst:20052541003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20244260001",
						"comment": "python3-idna is earlier than 0:2.5-7.el8_10"
					},
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20244260002",
						"comment": "python3-idna is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
