{
	"id": "oval:com.redhat.cve:def:202329483",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "dnspython: denial of service in stub resolver (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2023-29483",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-29483",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: The MITRE CVE dictionary describes this issue as: eventlet before 0.35.2, as used in dnspython before 2.6.0, allows remote attackers to interfere with DNS name resolution by quickly sending an invalid packet from the expected IP address and source port, aka a \"TuDoor\" attack. In other words, dnspython does not have the preferred behavior in which the DNS name resolution algorithm would proceed, within the full time window, in order to wait for a valid packet. NOTE: dnspython 2.6.0 is unusable for a different reason that was addressed in 2.6.1.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-04-12"
			},
			"cve": [
				{
					"text": "CVE-2023-29483",
					"cvss3": "5.9/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-696",
					"href": "https://access.redhat.com/security/cve/CVE-2023-29483",
					"impact": "moderate",
					"public": "20240209"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Affected",
						"component": [
							"python-dns",
							"python2-dns",
							"python27:2.7/python-dns",
							"python27:2.7/python2-dns"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:8",
					"cpe:/a:redhat:enterprise_linux:8::appstream",
					"cpe:/a:redhat:enterprise_linux:8::crb",
					"cpe:/a:redhat:enterprise_linux:8::highavailability",
					"cpe:/a:redhat:enterprise_linux:8::nfv",
					"cpe:/a:redhat:enterprise_linux:8::realtime",
					"cpe:/a:redhat:enterprise_linux:8::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:8::sap",
					"cpe:/a:redhat:enterprise_linux:8::sap_hana",
					"cpe:/a:redhat:enterprise_linux:8::supplementary",
					"cpe:/o:redhat:enterprise_linux:8",
					"cpe:/o:redhat:enterprise_linux:8::baseos"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202329483001",
										"comment": "python-dns is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202329483002",
										"comment": "python-dns is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:202329483003",
										"comment": "python2-dns is installed"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202329483004",
										"comment": "python2-dns is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterias": [
									{
										"operator": "OR",
										"criterias": [
											{
												"operator": "AND",
												"criterions": [
													{
														"test_ref": "oval:com.redhat.cve:tst:202329483001",
														"comment": "python-dns is installed"
													},
													{
														"test_ref": "oval:com.redhat.cve:tst:202329483002",
														"comment": "python-dns is signed with Red Hat redhatrelease2 key"
													}
												]
											},
											{
												"operator": "AND",
												"criterions": [
													{
														"test_ref": "oval:com.redhat.cve:tst:202329483003",
														"comment": "python2-dns is installed"
													},
													{
														"test_ref": "oval:com.redhat.cve:tst:202329483004",
														"comment": "python2-dns is signed with Red Hat redhatrelease2 key"
													}
												]
											}
										]
									}
								],
								"criterions": [
									{
										"test_ref": "oval:com.redhat.cve:tst:20074559015",
										"comment": "Module python27:2.7 is enabled"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20052541003",
						"comment": "Red Hat Enterprise Linux 8 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
