{
	"id": "oval:com.redhat.rhsa:def:20244766",
	"version": "637",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2024:4766: python3 security update (Low)",
		"reference": [
			{
				"ref_id": "RHSA-2024:4766",
				"ref_url": "https://access.redhat.com/errata/RHSA-2024:4766",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2024-4032",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-4032",
				"source": "CVE"
			}
		],
		"description": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: incorrect IPv4 and IPv6 private ranges (CVE-2024-4032)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Low",
			"updated": {
				"date": "2024-07-23"
			},
			"cve": [
				{
					"text": "CVE-2024-4032",
					"cvss3": "3.7/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"cwe": "CWE-440",
					"href": "https://access.redhat.com/security/cve/CVE-2024-4032",
					"impact": "low",
					"public": "20240617"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:enterprise_linux:9",
					"cpe:/a:redhat:enterprise_linux:9::appstream",
					"cpe:/a:redhat:enterprise_linux:9::crb",
					"cpe:/a:redhat:enterprise_linux:9::highavailability",
					"cpe:/a:redhat:enterprise_linux:9::nfv",
					"cpe:/a:redhat:enterprise_linux:9::realtime",
					"cpe:/a:redhat:enterprise_linux:9::resilientstorage",
					"cpe:/a:redhat:enterprise_linux:9::sap",
					"cpe:/a:redhat:enterprise_linux:9::sap_hana",
					"cpe:/a:redhat:enterprise_linux:9::supplementary",
					"cpe:/o:redhat:enterprise_linux:9",
					"cpe:/o:redhat:enterprise_linux:9::baseos"
				]
			},
			"rights": "Copyright 2024 Red Hat, Inc.",
			"issued": {
				"date": "2024-07-23"
			},
			"bugzilla": [
				{
					"text": "python: incorrect IPv4 and IPv6 private ranges",
					"href": "https://bugzilla.redhat.com/2292921",
					"id": "2292921"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 9"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766001",
										"comment": "python3.11 is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632016",
										"comment": "python3.11 is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766003",
										"comment": "python3.11-debug is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632018",
										"comment": "python3.11-debug is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766005",
										"comment": "python3.11-devel is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632020",
										"comment": "python3.11-devel is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766007",
										"comment": "python3.11-idle is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632010",
										"comment": "python3.11-idle is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766009",
										"comment": "python3.11-libs is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632026",
										"comment": "python3.11-libs is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766011",
										"comment": "python3.11-test is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632012",
										"comment": "python3.11-test is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20244766013",
										"comment": "python3.11-tkinter is earlier than 0:3.11.7-1.el9_4.3"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:202336632028",
										"comment": "python3.11-tkinter is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20052541003",
						"comment": "Red Hat Enterprise Linux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20052541004",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
