{
  "id": "oval:com.redhat.cve:def:202024584",
  "version": "636",
  "class": "vulnerability",
  "metadata": {
    "title": "CVE-2020-24584 django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+ (moderate)",
    "reference": [
      {
        "ref_id": "CVE-2020-24584",
        "ref_url": "https://access.redhat.com/security/cve/CVE-2020-24584",
        "source": "CVE"
      }
    ],
    "description": "DOCUMENTATION: A flaw was found in django. The intermediate-level directories of the file system cache had the system's standard umask rather than `0o077` (no group or others permissions). The highest threat from this vulnerability is to data confidentiality. \n            STATEMENT: This flaw can only be triggered in Django by using Python version 3.7 and newer. While the flawed package is shipped with the below Red Hat products, the flaw cannot be activated without manually updating Python to a newer release. This change would break many features and is an unsupported configuration.\n\n* Red Hat OpenStack Platform versions 15 and 16 ship Python 3.6.8; 10 and 13 ship Python 2.X.\n* Red Hat Ceph Storage 2 and 3 uses Python 2.X\n* Red Hat Gluster Storage 3 uses Python 2.X",
    "advisory": {
      "from": "secalert@redhat.com",
      "severity": "Moderate",
      "updated": {
        "date": "2021-12-14"
      },
      "cve": [
        {
          "text": "CVE-2020-24584",
          "cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "cwe": "CWE-276",
          "href": "https://access.redhat.com/security/cve/CVE-2020-24584",
          "impact": "moderate",
          "public": "20200901"
        }
      ],
      "affected": {
        "resolution": [
          {
            "state": "Out of support scope",
            "component": [
              "python-django",
              "python-django-bash-completion"
            ]
          }
        ]
      },
      "affected_cpe_list": {
        "cpe": [
          "cpe:/a:redhat:ceph_storage:2",
          "cpe:/a:redhat:ceph_storage:2::el7"
        ]
      },
      "issued": {}
    },
    "affected": {}
  },
  "criteria": {
    "operator": "OR",
    "criterias": [
      {
        "operator": "AND",
        "criterias": [
          {
            "operator": "OR",
            "criterias": [
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:20169014001",
                    "comment": "python-django is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:20169014002",
                    "comment": "python-django is signed with Red Hat redhatrelease2 key"
                  }
                ]
              },
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:20169014003",
                    "comment": "python-django-bash-completion is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:20169014004",
                    "comment": "python-django-bash-completion is signed with Red Hat redhatrelease2 key"
                  }
                ]
              }
            ]
          }
        ],
        "criterions": [
          {
            "test_ref": "oval:com.redhat.cve:tst:20137459003",
            "comment": "Red Hat Enterprise Linux 7 is installed"
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:com.redhat.cve:tst:20137459004",
        "comment": "Red Hat Enterprise Linux must be installed"
      }
    ]
  }
}
